FROM althack/ros2:humble-dev

ENV DEBIAN_FRONTEND=noninteractive

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | gpg --dearmor --batch --yes -o /usr/share/keyrings/ros-archive-keyring.gpg

# Add the ROS 2 repository for Jazzy (Ubuntu 24.04 is "noble")
RUN echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu noble main" > /etc/apt/sources.list.d/ros2.list

RUN apt update

RUN apt install -y git tini

RUN mkdir /app

WORKDIR /app

RUN pip install uv
RUN apt install binfmt-support -y

COPY utils/py-extension /usr/share/binfmts/py-extension

COPY utils/uv-runner /bin/uv-runner
RUN chmod +x /bin/uv-runner
RUN update-binfmts --import py-extension

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc

RUN echo 'export PATH="$PATH:/cmd"' >> /root/.bashrc

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD [ "/entrypoint.sh" ]